version: '3.7'

services:
  symfony_app:
    image: php:7.4-fpm
    container_name: symfony_app
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony_app
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_kubiweb
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
